### ISSUE TITLE
Webhook was not triggered

### ISSUE THREAD

**Issue by tnguyen14** [gglukmann/wp-trigger-github#2]
I have configured the settings (owner name, repo name, PAT and workflow name), and I can see the Deploy status badge on the Dashboard.

However, when I save a post, I'm not seeing a github actions build being triggered. I have set up the workflow with the following:

```yaml
on:
  repository_dispatch:
    types: [dispatch]
```

How could I debug this further?
